services:
  eureka-server:
    dns:
      - 8.8.8.8
      - 8.8.4.4
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: api-gateway
    container_name: api-gateway
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

  carts-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: carts-service
    container_name: carts-service
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - SERVER_PORT=8082
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_APPLICATION_NAME=carts-service
      - SPRING_DATA_MONGODB_URI=mongodb://carts-service-mongodb:27017/carts-service-mongodb
    depends_on:
      - eureka-server
      - carts-service-mongodb
    
  carts-service-mongodb:
      image: mongo:5.0
      container_name: carts-service-mongodb
      ports:
      - "5433:5433"
      volumes:
      - carts_db_data:/data/db

  catalog-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: catalog-service
    container_name: catalog-service
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - SERVER_PORT=8083
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_APPLICATION_NAME=catalog-service
    depends_on:
      - eureka-server

  listings-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: listings-service
    container_name: listings-service
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - SERVER_PORT=8084
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_APPLICATION_NAME=listings-service
      - MAVEN_OPTS="-Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true"
    depends_on:
      - eureka-server

  orders-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: orders-service
    container_name: orders-service
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - SERVER_PORT=8085
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_APPLICATION_NAME=orders-service
    depends_on:
      - eureka-server

  products-recommendations-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: products-recommendations-service
    container_name: products-recommendations-service
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - SERVER_PORT=8086
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_APPLICATION_NAME=products-recommendations-service
    depends_on:
      - eureka-server

  products-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: products-service
    container_name: products-service
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - SERVER_PORT=8087
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_APPLICATION_NAME=products-service
    depends_on:
      - eureka-server

  reviews-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: reviews-service
    container_name: reviews-service
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - SERVER_PORT=8088
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_APPLICATION_NAME=reviews-service
    depends_on:
      - eureka-server

  seller-daily-analytics-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: seller-daily-analytics-service
    container_name: seller-daily-analytics-service
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - SERVER_PORT=8089
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_APPLICATION_NAME=seller-daily-analytics-service
    depends_on:
      - eureka-server

  users-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: users-service
    container_name: users-service
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - SERVER_PORT=8081
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_APPLICATION_NAME=users-service
      # Postgres configuration
      - SPRING_DATASOURCE_URL=jdbc:postgresql://users-service-postgres:5432/users_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - eureka-server
      - users-service-postgres

  users-service-postgres:
    image: postgres:17.5-alpine
    container_name: users-service-postgres
    environment:
      - POSTGRES_DB=users_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - users_db_data:/var/lib/postgresql/data

volumes:
  users_db_data:
  carts_db_data: