services:
  eureka-server:
    volumes:
      - ./eureka-server:/app/eureka-server
      - ~/.m2:/root/.m2
    command: >
      sh -c "cd eureka-server &&
             mvn spring-boot:run"

  api-gateway:
    volumes:
      - ./api-gateway:/app/api-gateway
      - ~/.m2:/root/.m2
    command: >
      sh -c "cd api-gateway &&
             mvn spring-boot:run"

  auth-service:
    volumes:
      - ./auth-service:/app/auth-service
      - ~/.m2:/root/.m2
    command: >
      sh -c "cd auth-service &&
             mvn spring-boot:run"

  carts-service:
    volumes:
      - ./carts-service:/app/carts-service
      - ~/.m2:/root/.m2
    command: >
      sh -c "cd carts-service &&
             mvn spring-boot:run"

  catalog-service:
    volumes:
      - ./catalog-service:/app/catalog-service
      - ~/.m2:/root/.m2
    command: >
      sh -c "cd catalog-service &&
             mvn spring-boot:run"

  listings-service:
    volumes:
      - ./listings-service:/app/listings-service
      - ~/.m2:/root/.m2
    command: >
      sh -c "cd listings-service &&
             mvn spring-boot:run"

  orders-service:
    volumes:
      - ./orders-service:/app/orders-service
      - ~/.m2:/root/.m2
    command: >
      sh -c "cd orders-service &&
             mvn spring-boot:run"

  products-recommendations-service:
    volumes:
      - ./products-recommendations-service:/app/products-recommendations-service
      - ~/.m2:/root/.m2
    command: >
      sh -c "cd products-recommendations-service &&
             mvn spring-boot:run"

  products-service:
    volumes:
      - ./products-service:/app/products-service
      - ~/.m2:/root/.m2
    command: >
      sh -c "cd products-service &&
             mvn spring-boot:run"

  reviews-service:
    volumes:
      - ./reviews-service:/app/reviews-service
      - ~/.m2:/root/.m2
    command: >
      sh -c "cd reviews-service &&
             mvn spring-boot:run"

  seller-daily-analytics-service:
    volumes:
      - ./seller-daily-analytics-service:/app/seller-daily-analytics-service
      - ~/.m2:/root/.m2
    command: >
      sh -c "cd seller-daily-analytics-service &&
             mvn spring-boot:run"

  users-service:
    volumes:
      - ./users-service:/app/users-service
      - ~/.m2:/root/.m2
    command: >
      sh -c "cd users-service &&
             mvn spring-boot:run"