services:
  eureka-server:
    volumes:
      - ./eureka-server:/app/eureka-server
      - ~/.m2:/root/.m2
    command: >
      sh -c "cd eureka-server &&
             mvn spring-boot:run"

  api-gateway:
    volumes:
      - ./api-gateway:/app/api-gateway
      - ~/.m2:/root/.m2
    command: >
      sh -c "cd api-gateway &&
             mvn spring-boot:run"

  carts-service:
    volumes:
      - ./carts-service:/app/carts-service
      - ~/.m2:/root/.m2
    command: >
      sh -c "cd carts-service &&
             mvn spring-boot:run"

  listings-service:
    volumes:
      - ./listings-service:/app/listings-service
      - ~/.m2:/root/.m2
    command: >
      sh -c "cd listings-service &&
             mvn spring-boot:run"

  orders-service:
    volumes:
      - ./orders-service:/app/orders-service
      - ~/.m2:/root/.m2
    command: >
      sh -c "cd orders-service &&
             mvn spring-boot:run"

  reviews-service:
    volumes:
      - ./reviews-service:/app/reviews-service
      - ~/.m2:/root/.m2
    command: >
      sh -c "cd reviews-service &&
             mvn spring-boot:run"

  users-service:
    volumes:
      - ./users-service:/app/users-service
      - ~/.m2:/root/.m2
    command: >
      sh -c "cd users-service &&
             mvn spring-boot:run"