server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: users_service_route
          uri: lb://users-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2

        - id: carts_service_route
          uri: lb://carts-service
          predicates:
            - Path=/api/carts/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: carts-service-cb
                fallbackUri: forward:/fallback/carts

        - id: catalog_service_route
          uri: lb://catalog-service
          predicates:
            - Path=/api/catalog/**
          filters:
            - StripPrefix=2

        - id: listings_service_route
          uri: lb://listings-service
          predicates:
            - Path=/api/listings/**
          filters:
            - StripPrefix=2

        - id: orders_service_route
          uri: lb://orders-service
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=2

        - id: products_recommendations_service_route
          uri: lb://recommendations-service
          predicates:
            - Path=/api/recommendations/**
          filters:
            - StripPrefix=2

        - id: reviews_service_route
          uri: lb://reviews-service
          predicates:
            - Path=/api/reviews/**
          filters:
            - StripPrefix=2

        - id: seller_daily_analytics_service_route
          uri: lb://seller-daily-analytics-service
          predicates:
            - Path=/api/analytics/**
          filters:
            - StripPrefix=2

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.cors: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
