server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: rota_servico_exemplo
          # 'lb' significa Load Balancer. O Gateway usará o Eureka para encontrar uma instância de 'MS-SERVICO-EXEMPLO'
          uri: lb://MS-SERVICO-EXEMPLO
          predicates:
            # Qualquer requisição para /api/exemplo/** será roteada
            - Path=/api/exemplo/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: gateway