server:
  port: 0

spring:
  application:
    name: orders-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      uuid-representation: java_legacy
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

logging:
  level:
    root: INFO # Or DEBUG if you want verbose logs for everything
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG # THIS MUST BE DEBUG
      bson:
        Document: DEBUG # Good to have
      mongodb:
        driver: DEBUG # Good to have