server:
  port: 0

spring:
  application:
    name: carts-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  kafka:
    consumer:
      group-id: "carts-service-group"

logging:
  level:
    com.mercadonosso.carts_service: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.cors: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

app:
  services:
    listings-url: http://listings-service

topics:
  cart-clear:
    name: "com.mercadonosso.carts.event.cleared"
  cart-remove:
    name: "com.mercadonosso.carts.event.remove"
