server:
  port: 8088

spring:
  application:
    name: reviews-service
  data:
    mongodb:
      uri: mongodb://reviews-service-mongodb:27017/reviews_db

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

app:
  services:
    listings-url: http://listings-service:8084
